#!/bin/bash

function createFarmer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/farmer.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/farmer.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-farmer --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/farmer.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy farmer's CA cert to farmer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/farmer.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/farmer.example.com/msp/tlscacerts/ca.crt"

  # Copy farmer's CA cert to farmer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/farmer.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/farmer.example.com/tlsca/tlsca.farmer.example.com-cert.pem"

  # Copy farmer's CA cert to farmer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/farmer.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/farmer.example.com/ca/ca.farmer.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-farmer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-farmer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-farmer --id.name farmeradmin --id.secret farmeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-farmer -M "${PWD}/organizations/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/msp" --csr.hosts peer0.farmer.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/farmer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-farmer -M "${PWD}/organizations/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/tls" --enrollment.profile tls --csr.hosts peer0.farmer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-farmer -M "${PWD}/organizations/peerOrganizations/farmer.example.com/users/User1@farmer.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/farmer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/farmer.example.com/users/User1@farmer.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://farmeradmin:farmeradminpw@localhost:7054 --caname ca-farmer -M "${PWD}/organizations/peerOrganizations/farmer.example.com/users/Admin@farmer.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/farmer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/farmer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/farmer.example.com/users/Admin@farmer.example.com/msp/config.yaml"
}

function createLogistics() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/logistics.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/logistics.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-logistics --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-logistics.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-logistics.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-logistics.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-logistics.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/logistics.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy logistics's CA cert to logistics's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/logistics.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem" "${PWD}/organizations/peerOrganizations/logistics.example.com/msp/tlscacerts/ca.crt"

  # Copy logistics's CA cert to logistics's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/logistics.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem" "${PWD}/organizations/peerOrganizations/logistics.example.com/tlsca/tlsca.logistics.example.com-cert.pem"

  # Copy logistics's CA cert to logistics's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/logistics.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem" "${PWD}/organizations/peerOrganizations/logistics.example.com/ca/ca.logistics.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-logistics --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-logistics --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-logistics --id.name logisticsadmin --id.secret logisticsadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-logistics -M "${PWD}/organizations/peerOrganizations/logistics.example.com/peers/peer0.logistics.example.com/msp" --csr.hosts peer0.logistics.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/logistics.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/logistics.example.com/peers/peer0.logistics.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-logistics -M "${PWD}/organizations/peerOrganizations/logistics.example.com/peers/peer0.logistics.example.com/tls" --enrollment.profile tls --csr.hosts peer0.logistics.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/logistics.example.com/peers/peer0.logistics.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/logistics.example.com/peers/peer0.logistics.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/logistics.example.com/peers/peer0.logistics.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/logistics.example.com/peers/peer0.logistics.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/logistics.example.com/peers/peer0.logistics.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/logistics.example.com/peers/peer0.logistics.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-logistics -M "${PWD}/organizations/peerOrganizations/logistics.example.com/users/User1@logistics.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/logistics.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/logistics.example.com/users/User1@logistics.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://logisticsadmin:logisticsadminpw@localhost:8054 --caname ca-logistics -M "${PWD}/organizations/peerOrganizations/logistics.example.com/users/Admin@logistics.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/logistics/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/logistics.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/logistics.example.com/users/Admin@logistics.example.com/msp/config.yaml"
}

function createWarehouse() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/warehouse.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/warehouse.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-warehouse --tls.certfiles "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-warehouse.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-warehouse.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-warehouse.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-warehouse.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/warehouse.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy warehouse's CA cert to warehouse's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/warehouse.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem" "${PWD}/organizations/peerOrganizations/warehouse.example.com/msp/tlscacerts/ca.crt"

  # Copy warehouse's CA cert to warehouse's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/warehouse.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem" "${PWD}/organizations/peerOrganizations/warehouse.example.com/tlsca/tlsca.warehouse.example.com-cert.pem"

  # Copy warehouse's CA cert to warehouse's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/warehouse.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem" "${PWD}/organizations/peerOrganizations/warehouse.example.com/ca/ca.warehouse.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-warehouse --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-warehouse --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-warehouse --id.name warehouseadmin --id.secret warehouseadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9054 --caname ca-warehouse -M "${PWD}/organizations/peerOrganizations/warehouse.example.com/peers/peer0.warehouse.example.com/msp" --csr.hosts peer0.warehouse.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/warehouse.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/warehouse.example.com/peers/peer0.warehouse.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9054 --caname ca-warehouse -M "${PWD}/organizations/peerOrganizations/warehouse.example.com/peers/peer0.warehouse.example.com/tls" --enrollment.profile tls --csr.hosts peer0.warehouse.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/warehouse.example.com/peers/peer0.warehouse.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/warehouse.example.com/peers/peer0.warehouse.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/warehouse.example.com/peers/peer0.warehouse.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/warehouse.example.com/peers/peer0.warehouse.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/warehouse.example.com/peers/peer0.warehouse.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/warehouse.example.com/peers/peer0.warehouse.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:9054 --caname ca-warehouse -M "${PWD}/organizations/peerOrganizations/warehouse.example.com/users/User1@warehouse.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/warehouse.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/warehouse.example.com/users/User1@warehouse.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://warehouseadmin:warehouseadminpw@localhost:9054 --caname ca-warehouse -M "${PWD}/organizations/peerOrganizations/warehouse.example.com/users/Admin@warehouse.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/warehouse/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/warehouse.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/warehouse.example.com/users/Admin@warehouse.example.com/msp/config.yaml"
}

function createBuyer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/buyer.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/buyer.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-buyer --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-buyer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-buyer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-buyer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-buyer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy buyer's CA cert to buyer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/tlscacerts/ca.crt"

  # Copy buyer's CA cert to buyer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/buyer.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/buyer.example.com/tlsca/tlsca.buyer.example.com-cert.pem"

  # Copy buyer's CA cert to buyer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/buyer.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/buyer.example.com/ca/ca.buyer.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-buyer --id.name buyeradmin --id.secret buyeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/msp" --csr.hosts peer0.buyer.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls" --enrollment.profile tls --csr.hosts peer0.buyer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/buyer.example.com/peers/peer0.buyer.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/users/User1@buyer.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.example.com/users/User1@buyer.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://buyeradmin:buyeradminpw@localhost:10054 --caname ca-buyer -M "${PWD}/organizations/peerOrganizations/buyer.example.com/users/Admin@buyer.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/buyer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/buyer.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/buyer.example.com/users/Admin@buyer.example.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:11054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp" --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:11054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls" --enrollment.profile tls --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:11054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
